# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    defaults:
      run:
        working-directory: playground

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1.4.2
          
    - run: yarn install
      
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        path: node_modules/
        key: yarn-${{ hashFiles('**/package-lock.json') }}
      
    - run: yarn build
    - run: yarn deploy
